from synthex import Synthex
from datasets import ClassLabel
from transformers import AutoModelForSequenceClassification, PreTrainedModel, AutoTokenizer, \
    PreTrainedTokenizerBase
from transformers.trainer_utils import TrainOutput
from typing import Optional

from ..nclass_classification_model import NClassClassificationModel

from artifex.core import auto_validate_methods
from artifex.config import config


@auto_validate_methods
class SentimentAnalysis(NClassClassificationModel):
    """
    A Sentiment Analysis Model is used to classify the sentiment of a given text into predefined 
    categories, typically `positive`, `negative`, or `neutral`. In this implementation, we 
    support two extra sentiment categories: `very_positive` and `very_negative`.
    """

    def __init__(self, synthex: Synthex):
        """
        Initializes the class with a Synthex instance.
        Args:
            synthex (Synthex): An instance of the Synthex class to generate the synthetic 
                data used to train the model.
        """
        super().__init__(synthex)
        self._base_model_name_val: str = config.SENTIMENT_ANALYSIS_HF_BASE_MODEL
        self._system_data_gen_instr_val: list[str] = [
            "The 'text' field should contain text that belongs to the following domain(s): {domain}.",
            "The 'text' field should contain text that may or may not express a certain sentiment.",
            "The 'labels' field should contain a label indicating the sentiment of the 'text'.",
            "'labels' must only contain one of the provided labels; under no circumstances should it contain arbitrary text.",
            "This is a list of the allowed 'labels' and their meaning: "
        ]
        self._model_val: PreTrainedModel = AutoModelForSequenceClassification.from_pretrained(
            self._base_model_name
        )
        self._tokenizer_val: PreTrainedTokenizerBase = AutoTokenizer.from_pretrained(
            self._base_model_name, use_fast=False
        )
        id2label = getattr(self._model_val.config, "id2label", None)
        if id2label is None:
            raise ValueError(f"Model {self._base_model_name} does not have id2label configuration")
        self._labels_val: ClassLabel = ClassLabel(
            names=list(id2label.values())
        )
        
    @property
    def _base_model_name(self) -> str:
        return self._base_model_name_val
    
    @property
    def _system_data_gen_instr(self) -> list[str]:
        return self._system_data_gen_instr_val

    def train(
        self, domain: str, classes: Optional[dict[str, str]] = None, 
        output_path: Optional[str] = None, num_samples: int = config.DEFAULT_SYNTHEX_DATAPOINT_NUM, 
        num_epochs: int = 3
    ) -> TrainOutput:
        f"""
        Train the Sentiment Analysis model using synthetic data generated by Synthex.
        
        NOTE: this method overrides `NClassClassificationModel.train()` to make the `classes` 
        parameter optional.
        
        Args:
            domain (str): A description of the domain or context for which the model is being trained.
            classes (dict[str, str]): A dictionary mapping class names to their descriptions. The keys 
                (class names) must be string with no spaces and a maximum length of 
                {config.CLASSIFICATION_CLASS_NAME_MAX_LENGTH} characters.
            output_path (Optional[str]): The path where the generated synthetic data will be saved.
            num_samples (int): The number of training data samples to generate.
            num_epochs (int): The number of epochs for training the model.
        """
        
        if classes is None:
            classes = {
                "very_negative": "Text that expresses a very negative sentiment or strong dissatisfaction.",
                "negative": "Text that expresses a negative sentiment or dissatisfaction.",
                "neutral": "Either a text that does not express any sentiment at all, or a text that expresses a neutral sentiment or lack of strong feelings.",
                "positive": "Text that expresses a positive sentiment or satisfaction.",
                "very_positive": "Text that expresses a very positive sentiment or strong satisfaction."
            }
        
        return super().train(
            domain=domain, classes=classes, output_path=output_path, 
            num_samples=num_samples, num_epochs=num_epochs
        )
