from synthex import Synthex
from typing import Optional
from transformers import AutoConfig, AutoModelForSequenceClassification
from transformers.trainer_utils import TrainOutput
from datasets import ClassLabel

from ...classification_model import ClassificationModel

from artifex.core import auto_validate_methods, ParsedModelInstructions, track_training_calls, ValidationError
from artifex.config import config


@auto_validate_methods
class ThreatDetection(ClassificationModel):
    """
    A multi-class classification model for detecting cybersecurity threats in log entries.
    Classifies log lines into one of the following categories: `no_threat`, `brute_force`,
    `sql_injection`, `ddos`, `malware`, `unauthorized_access`.
    """

    def __init__(self, synthex: Synthex):
        """
        Initializes the class with a Synthex instance.
        Args:
            synthex (Synthex): An instance of the Synthex class to generate the synthetic data used to train
                the model.
        """

        super().__init__(synthex, base_model_name=config.THREAT_DETECTION_HF_BASE_MODEL)
        self._system_data_gen_instr_val: list[str] = [
            "The 'text' field should contain a log entry (e.g. web server access log, auth log, system log, firewall log).",
            "The 'labels' field should contain a label indicating the type of cybersecurity threat present in the log entry, or 'no_threat' if the log entry is benign.",
            "The 'labels' field can only have one of these values: 'no_threat', 'brute_force', 'sql_injection', 'ddos', 'malware', 'unauthorized_access'.",
            "The dataset should contain an approximately equal number of samples for each label.",
            "The following log patterns and activities should be considered as threats: {threat_indicators}.",
            "Log entries that do not match any threat pattern should be labeled 'no_threat'.",
            "The dataset should also contain realistic log entries not explicitly mentioned in these instructions, labeled appropriately.",
        ]
        self._labels_val: ClassLabel = ClassLabel(
            names=["no_threat", "brute_force", "sql_injection", "ddos", "malware", "unauthorized_access"]
        )

    def _get_data_gen_instr(self, user_instr: ParsedModelInstructions) -> list[str]:
        """
        Overrides `ClassificationModel._get_data_gen_instr` to format instructions for threat detection.
        Args:
            user_instr (ParsedModelInstructions): Parsed user instructions containing threat indicators.
        Returns:
            list[str]: A list of formatted data generation instructions.
        """

        out = [
            instr.format(threat_indicators=user_instr.user_instructions)
            for instr in self._system_data_gen_instr_val
        ]
        return out

    def _parse_user_instructions(
        self, user_instructions: list[str], language: str
    ) -> ParsedModelInstructions:
        """
        Convert user-provided threat indicators into a ParsedModelInstructions object.
        Args:
            user_instructions (list[str]): A list of strings describing threat patterns or activities
                specific to the target environment.
            language (str): The language to use for generating the training dataset.
        Returns:
            ParsedModelInstructions: The parsed user instructions.
        """

        return ParsedModelInstructions(
            user_instructions=user_instructions,
            language=language
        )

    @track_training_calls
    def train(
        self, threat_indicators: Optional[list[str]] = None, output_path: Optional[str] = None,
        num_samples: int = config.DEFAULT_SYNTHEX_DATAPOINT_NUM, num_epochs: int = 3,
        device: Optional[int] = None, disable_logging: Optional[bool] = False,
        train_dataset_path: Optional[str] = None
    ) -> TrainOutput:
        f"""
        Train the ThreatDetection model using synthetic log data generated by Synthex.
        Args:
            threat_indicators (Optional[list[str]]): A list of strings describing log patterns or
                activities that should be classified as threats. Required when `train_dataset_path`
                is not provided.
            output_path (Optional[str]): The path where the synthetic training data and the output
                model will be saved.
            num_samples (int): The number of training data samples to generate. Defaults to
                {config.DEFAULT_SYNTHEX_DATAPOINT_NUM}.
            num_epochs (int): The number of epochs for training the model. Defaults to 3.
            device (Optional[int]): The device to perform training on. If None, uses GPU if
                available, otherwise CPU.
            disable_logging (Optional[bool]): Whether to disable logging during training. Defaults to False.
            train_dataset_path (Optional[str]): Path to an existing training dataset CSV file. If
                provided, synthetic data generation is skipped.
        Returns:
            TrainOutput: The output of the training process.
        """

        if train_dataset_path is None and threat_indicators is None:
            raise ValidationError(
                message="The `threat_indicators` parameter is required when `train_dataset_path` is not provided."
            )

        label_names = self._labels.names
        model_config = AutoConfig.from_pretrained(self._base_model_name)
        model_config.num_labels = len(label_names)
        model_config.id2label = {i: name for i, name in enumerate(label_names)}
        model_config.label2id = {name: i for i, name in enumerate(label_names)}
        self._model = AutoModelForSequenceClassification.from_pretrained(
            self._base_model_name,
            config=model_config,
            ignore_mismatched_sizes=True
        )

        user_instructions = self._parse_user_instructions(
            user_instructions=threat_indicators,
            language="english"
        ) if threat_indicators is not None else None

        output: TrainOutput = self._train_pipeline(
            user_instructions=user_instructions, output_path=output_path, num_samples=num_samples,
            num_epochs=num_epochs, device=device,
            train_dataset_path=train_dataset_path
        )

        return output
