from synthex import Synthex
from datasets import ClassLabel # type: ignore
from transformers import AutoModelForSequenceClassification, PreTrainedModel, AutoTokenizer, \
    PreTrainedTokenizerBase
from transformers.trainer_utils import TrainOutput
from typing import Optional

from artifex.models.nclass_classification_model import NClassClassificationModel
from artifex.core import auto_validate_methods
from artifex.config import config


@auto_validate_methods
class EmotionDetection(NClassClassificationModel):
    """
    An Emotion Detection Model is used to classify text into different emotional categories. In this 
    implementation, we support the following emotions: `joy`, `anger`, `fear`, `sadness`, `surprise`, `disgust`, 
    `excitement` and `neutral`.
    """

    def __init__(self, synthex: Synthex):
        """
        Initializes the class with a Synthex instance.
        Args:
            synthex (Synthex): An instance of the Synthex class to generate the synthetic 
                data used to train the model.
        """
        super().__init__(synthex)
        self._base_model_name_val: str = config.EMOTION_DETECTION_HF_BASE_MODEL
        self._system_data_gen_instr: list[str] = [
            "The 'text' field should contain text that may or may not express a certain emotion.",
            "The 'labels' field should contain a label indicating the emotion of the 'text'.",
            "'labels' must only contain one of the provided labels; under no circumstances should it contain arbitrary text.",
            "This is a list of the allowed 'labels' and 'text' pairs: "
        ]
        self._model_val: PreTrainedModel = AutoModelForSequenceClassification.from_pretrained( # type: ignore
            self._base_model_name
        )
        self._tokenizer_val: PreTrainedTokenizerBase = AutoTokenizer.from_pretrained( # type: ignore
            self._base_model_name, use_fast=False
        )
        self._labels_val: ClassLabel = ClassLabel(
            names=list(self._model_val.config.id2label.values()) # type: ignore
        )
        
    @property
    def _base_model_name(self) -> str:
        return self._base_model_name_val
    
    def _get_data_gen_instr(self, user_instr: list[str]) -> list[str]:
        return self._system_data_gen_instr + user_instr
        
    def train(
        self, domain: str, classes: dict[str, str], output_path: Optional[str] = None, 
        num_samples: int = config.DEFAULT_SYNTHEX_DATAPOINT_NUM, 
        num_epochs: int = 3
    ) -> TrainOutput:
        f"""
        Train the Emotion Detection model using synthetic data generated by Synthex.
        
        NOTE: this method overrides `NClassClassificationModel.train()` to add the `domain` parameter 
        and make the `classes` parameter optional.
        
        Args:
            domain (str): A description of the domain or context for which the model is being trained.
            classes (dict[str, str]): A dictionary mapping class names to their descriptions. The keys 
                (class names) must be string with no spaces and a maximum length of 
                {config.NCLASS_CLASSIFICATION_CLASSNAME_MAX_LENGTH} characters.
            output_path (Optional[str]): The path where the generated synthetic data will be saved.
            num_samples (int): The number of training data samples to generate.
            num_epochs (int): The number of epochs for training the model.
        """
        
        return super().train(
            domain=domain, classes=classes, output_path=output_path, 
            num_samples=num_samples, num_epochs=num_epochs
        )
