from synthex import Synthex
from datasets import ClassLabel # type: ignore
from transformers import AutoModelForSequenceClassification, PreTrainedModel, AutoTokenizer, \
    PreTrainedTokenizerBase
from transformers.trainer_utils import TrainOutput
from typing import Optional

from artifex.models.nclass_classification_model import NClassClassificationModel
from artifex.core import auto_validate_methods
from artifex.config import config


@auto_validate_methods
class SentimentAnalysis(NClassClassificationModel):
    """
    A Sentiment Analysis Model is used to classify the sentiment of a given text into predefined 
    categories, typically `positive`, `negative`, or `neutral`. In this implementation, we 
    optionally support two extra sentiment categories: `very_positive` and `very_negative`.
    """

    def __init__(self, synthex: Synthex):
        """
        Initializes the class with a Synthex instance.
        Args:
            synthex (Synthex): An instance of the Synthex class to generate the synthetic 
                data used to train the model.
        """
        
        super().__init__(synthex)
        self._system_data_gen_instr: list[str] = [
            "The 'text' field should contain text that may or may not express a certain sentiment.",
            "The 'labels' field should contain a label indicating the sentiment of the 'text'.",
            "'labels' must only contain one of the provided labels; under no circumstances should it contain arbitrary text.",
            "This is a list of the allowed 'labels' and 'text' pairs: "
        ]
        self._model_val: PreTrainedModel = AutoModelForSequenceClassification.from_pretrained( # type: ignore
            config.SENTIMENT_ANALYSIS_HF_BASE_MODEL
        )
        self._tokenizer_val: PreTrainedTokenizerBase = AutoTokenizer.from_pretrained( # type: ignore
            config.SENTIMENT_ANALYSIS_HF_BASE_MODEL
        )
        self._labels_val: ClassLabel = ClassLabel(
            names=list(self._model_val.config.id2label.values()) # type: ignore
        )
    
    def _get_data_gen_instr(self, user_instr: list[str]) -> list[str]:
        return self._system_data_gen_instr + user_instr
        
    def train(
        self, classes: Optional[dict[str, str]] = None, output_path: Optional[str] = None, 
        num_samples: int = config.DEFAULT_SYNTHEX_DATAPOINT_NUM, num_epochs: int = 3
    ) -> TrainOutput:
        f"""
        Train the Sentiment Analysis model using synthetic data generated by Synthex.
        
        NOTE: this method overrides `NClassClassificationModel.train()` to make the `classes` parameter 
        optional.
        
        Args:
            classes (dict[str, str]): A dictionary mapping class names to their descriptions. The keys 
                (class names) must be string with no spaces and a maximum length of 
                {config.INTENT_CLASSIFIER_CLASSNAME_MAX_LENGTH} characters.
            output_path (Optional[str]): The path where the generated synthetic data will be saved.
            num_samples (int): The number of training data samples to generate.
            num_epochs (int): The number of epochs for training the model.
        """
        
        if classes is None:
            classes = {
                "very_negative": "Text that expresses a very negative sentiment or strong dissatisfaction.",
                "negative": "Text that expresses a negative sentiment or dissatisfaction.",
                "neutral": "Text that expresses a neutral sentiment or lack of strong feelings.",
                "positive": "Text that expresses a positive sentiment or satisfaction.",
                "very_positive": "Text that expresses a very positive sentiment or strong satisfaction."
            }
        
        return super().train(
            classes=classes, output_path=output_path, num_samples=num_samples, num_epochs=num_epochs
        )
